// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt9aziwiqDEWx_M76wkVzR6voqSWPtWk0',
    appId: '1:820134648228:web:89138278ccd8f8c5d48931',
    messagingSenderId: '820134648228',
    projectId: 'mpc-wallet-6a4b0',
    authDomain: 'mpc-wallet-6a4b0.firebaseapp.com',
    storageBucket: 'mpc-wallet-6a4b0.appspot.com',
    measurementId: 'G-054KSJ2FHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ivIZsHHc75W5GopUeTiZQUQF-ysbex0',
    appId: '1:820134648228:android:c218d3cf94718088d48931',
    messagingSenderId: '820134648228',
    projectId: 'mpc-wallet-6a4b0',
    storageBucket: 'mpc-wallet-6a4b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmPbP3xG_34VYFuY2KFjie1uv_Q-jqfnk',
    appId: '1:820134648228:ios:ce5c9d586b1e2a23d48931',
    messagingSenderId: '820134648228',
    projectId: 'mpc-wallet-6a4b0',
    storageBucket: 'mpc-wallet-6a4b0.appspot.com',
    iosClientId: '820134648228-pscbs9kti4lsutihanpfpvta2usfo09r.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmPbP3xG_34VYFuY2KFjie1uv_Q-jqfnk',
    appId: '1:820134648228:ios:ce5c9d586b1e2a23d48931',
    messagingSenderId: '820134648228',
    projectId: 'mpc-wallet-6a4b0',
    storageBucket: 'mpc-wallet-6a4b0.appspot.com',
    iosClientId: '820134648228-pscbs9kti4lsutihanpfpvta2usfo09r.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
